# This is a basic workflow to help you get started with Actions

name: hello-world
env: 
  APP_NAME     : "FLASK"
  PACKAGE_NAME : "FLASK DEPLOY VERSION 1.0 -${{ github.sha }}"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps job
    steps:       
      - name: Run a one-line build script 
        run: echo Hello, world!
      - name: Print global variables
        run: |
           echo "${{ env.APP_NAME }}"
      - name: Git clone repo
        uses: actions/checkout@v1
        
      - name: List files and folders
        run: ls -lah
     
           
  my-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [my-build]
    env: 
      VAR1: "VAR number 1"
      VAR2: "VAR number 2"
    
    # Steps job
    steps:       
      - name: Run a one-line test script
        run: echo Hello, test!
      - name: Run local vars
        run: |
          echo "var 1 = ${{ env.VAR1 }}"
          echo LOC_VAR
      - name: Lets test code
        run: aws --version
      - name:  Docker version
        run: docker --version
        env:
          LOC_VAR: "This is local variable" 
         
      - name:  zip version
        run: zip --version
        
      - name: Print package name
        run: echo "Package name - ${{ env.PACKAGE_NAME }}"
